AllowUsers loop-worker@135.106.211.64

Match User loop-worker
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitTTY no
    DisableForwarding yes
    X11Forwarding no
    PermitTunnel no
    PermitUserEnvironment no
    ForceCommand /opt/loop/worker_ssh.py
