Port 18180
Listen 172.30.240.1
Timeout 900
LogLevel Error
Syslog On
PidFile "/run/loop-proxy/tinyproxy.pid"
MaxClients 16
Allow 172.30.240.2
ConnectPort 443
DisableViaHeader Yes
Upstream socks5 127.0.0.1:18181
